### ISSUE TITLE
docker-compose来跑服务,竟然不让跑

### ISSUE THREAD

**Issue by Error996** [Char1esOrz/minerProxy#7]
暗抽么?
![image](https://user-images.githubusercontent.com/12880110/147337219-ca0bfe51-d38b-41a2-9420-181714ef81f1.png)
![image](https://user-images.githubusercontent.com/12880110/147337303-08b1d63a-bc79-4148-be00-7797b2038f30.png)
这有点意思了

**Comment by Error996** [comment]
```
version: '3.7'

services:
  MinerServer:
    restart: always
    image: busybox:stable-glibc
    hostname: MinerServer
    working_dir: /root
    volumes:
        - './minerpool:/root:ro'
    networks:
      - no-internet
    command: '/root/miner'
  Forward:
    image: busybox:stable-glibc
    hostname: Forward
    volumes:
        - './gost:/root'
    networks:
      - no-internet
      - internet
    command: '/root/gost -L=tcp://:443/eth-hk.ss.poolin.me:443'
  Web:
    image: busybox:stable-glibc
    hostname: Forward
    volumes:
        - './gost:/root'
    ports:
        - "18888:18888"
    networks:
      - no-internet
      - internet
    command: '/root/gost -L=tcp://:18888/root_MinerServer_1:18888'
  Worker:
    image: busybox:stable-glibc
    hostname: Forward
    volumes:
        - './gost:/root'
    ports:
        - "1883:1883"
    networks:
      - no-internet
      - internet
    command: '/root/gost -L=tcp://:1883/root_MinerServer_1:1883'
networks:
  no-internet:
    driver: bridge
    internal: true
    ipam:
        config:
            - subnet: 172.19.0.0/16
  internet:
    driver: bridge

```

**Comment by Error996** [comment]
```
host: 0.0.0.0
port: 18888
token: PPZJOZXOOKKJNHJLCYGTPSEMSHLWIDRB
webserver: true
server:
    - port: "1883"
      ssl: 0
      proxypool: tcp://172.19.0.4:443
      devfee: 0.5
      devpool: tcp://172.19.0.4:443
      addr: test
      worker: devfee22
      reconnect: 20
      clientnum: 0

```
172.19.0.4为Forward的内部ip,容器之间胡通,Forward可访问互联网
